2021-11-22 00:00:03,628   DEBUG      server.py    Function: set_up, args: (<__main__.Server object at 0x000001CFD17E3E20>,), kwargs: {}, called from function: <module>
2021-11-22 00:00:03,630   INFO       server.py    server started at 7777 and listened all ip
2021-11-22 00:01:01,334   DEBUG      server.py    Function: set_up, args: (<__main__.Server object at 0x000001BBA0173E20>,), kwargs: {}, called from function: <module>
2021-11-22 00:01:01,335   INFO       server.py    server started at 7777 and listened all ip
2021-11-22 00:02:49,579   DEBUG      server.py    Function: set_up, args: (<__main__.Server object at 0x0000028859423EB0>,), kwargs: {}, called from function: <module>
2021-11-22 00:02:49,581   INFO       server.py    server started at 7777 and listened all ip
2021-11-22 00:03:27,124   DEBUG      server.py    Function: set_up, args: (<__main__.Server object at 0x00000190D7973E80>,), kwargs: {}, called from function: <module>
2021-11-22 00:03:27,125   INFO       server.py    server started at 7777 and listened all ip
2021-11-22 00:04:22,572   DEBUG      server.py    Function: set_up, args: (<__main__.Server object at 0x0000019135C83EB0>,), kwargs: {}, called from function: <module>
2021-11-22 00:04:22,573   INFO       server.py    server started at 7777 and listened all ip
2021-11-22 00:05:07,288   DEBUG      server.py    Function: set_up, args: (<__main__.Server object at 0x000001DBF9863EB0>,), kwargs: {}, called from function: <module>
2021-11-22 00:05:07,289   INFO       server.py    server started at 7777 and listened all ip
2021-11-22 00:05:14,776   DEBUG      server.py    Function: set_up, args: (<__main__.Server object at 0x000002D377413EB0>,), kwargs: {}, called from function: <module>
2021-11-22 00:05:14,780   INFO       server.py    server started at 7777 and listened all ip
2021-11-22 00:06:29,316   DEBUG      server.py    Function: set_up, args: (<__main__.Server object at 0x0000022049BF3FD0>,), kwargs: {}, called from function: <module>
2021-11-22 00:06:29,318   INFO       server.py    server started at 7777 and listened all ip
2021-11-22 00:06:44,900   DEBUG      server.py    Function: set_up, args: (<__main__.Server object at 0x000001DDF9233FA0>,), kwargs: {}, called from function: <module>
2021-11-22 00:06:44,901   INFO       server.py    server started at 7777 and listened all ip
2021-11-22 00:08:30,229   INFO       server.py    server started at 7777 and listened all ip
2021-11-22 00:15:03,536   INFO       server.py    ('127.0.0.1', 52177): client connection established
2021-11-22 00:15:04,586   DEBUG      server.py    Function: handle_message, args: (<__main__.Server object at 0x00000237F25E3E20>, {'action': 'presence', 'time': 1637529303.5600538, 'user': {'account_name': 'Guest', 'status': 'online'}, 'type': 'status'}, <socket.socket fd=328, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 52177)>), kwargs: {}, called from function: set_up
2021-11-22 00:15:04,586   INFO       server.py    ('127.0.0.1', 52177): the message from the client is being handled
2021-11-22 00:15:04,586   INFO       server.py    ('127.0.0.1', 52177): name 'Guest' status 'online'
2021-11-22 00:15:04,586   INFO       server.py    ('127.0.0.1', 52177): name 'Guest' added into clients_usernames
2021-11-22 00:15:42,339   INFO       server.py    ('127.0.0.1', 52180): client connection established
2021-11-22 00:15:42,340   INFO       server.py    ('127.0.0.1', 52177): client disconnected
2021-11-22 00:15:42,340   INFO       server.py    [WinError 10054] Удаленный хост принудительно разорвал существующее подключение
2021-11-22 00:15:43,349   DEBUG      server.py    Function: handle_message, args: (<__main__.Server object at 0x00000237F25E3E20>, {'action': 'presence', 'time': 1637529342.3988953, 'user': {'account_name': 'Guest', 'status': 'online'}, 'type': 'status'}, <socket.socket fd=420, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 52180)>), kwargs: {}, called from function: set_up
2021-11-22 00:15:43,349   INFO       server.py    ('127.0.0.1', 52180): the message from the client is being handled
2021-11-22 00:15:43,349   INFO       server.py    ('127.0.0.1', 52180): name 'Guest' status 'online'
2021-11-22 00:15:43,349   INFO       server.py    ('127.0.0.1', 52180): name 'Guest' added into clients_usernames
2021-11-22 00:16:10,609   INFO       server.py    ('127.0.0.1', 52180): client disconnected
2021-11-22 00:16:10,609   INFO       server.py    [WinError 10054] Удаленный хост принудительно разорвал существующее подключение
2021-11-22 00:17:45,603   INFO       server.py    ('127.0.0.1', 52186): client connection established
2021-11-22 00:17:46,607   DEBUG      server.py    Function: handle_message, args: (<__main__.Server object at 0x00000237F25E3E20>, {'action': 'presence', 'time': 1637529465.630091, 'user': {'account_name': 'Guest', 'status': 'online'}, 'type': 'status'}, <socket.socket fd=360, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 52186)>), kwargs: {}, called from function: set_up
2021-11-22 00:17:46,608   INFO       server.py    ('127.0.0.1', 52186): the message from the client is being handled
2021-11-22 00:17:46,608   INFO       server.py    ('127.0.0.1', 52186): name 'Guest' status 'online'
2021-11-22 00:17:46,608   INFO       server.py    ('127.0.0.1', 52186): name 'Guest' added into clients_usernames
2021-11-22 00:18:42,762   INFO       server.py    server started at 7777 and listened all ip
2021-11-22 00:24:08,395   INFO       server.py    ('127.0.0.1', 52213): client connection established
2021-11-22 00:24:09,426   DEBUG      server.py    Function: handle_message, args: (<__main__.Server object at 0x0000022F15852350>, {'action': 'presence', 'time': 1637529848.419552, 'user': {'account_name': 'Guest', 'status': 'online'}, 'type': 'status'}, <socket.socket fd=352, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 52213)>), kwargs: {}, called from function: set_up
2021-11-22 00:24:09,426   INFO       server.py    ('127.0.0.1', 52213): the message from the client is being handled
2021-11-22 00:24:09,427   INFO       server.py    ('127.0.0.1', 52213): name 'Guest' status 'online'
2021-11-22 00:24:09,427   INFO       server.py    ('127.0.0.1', 52213): name 'Guest' added into clients_usernames
2021-11-22 00:24:54,739   INFO       server.py    ('127.0.0.1', 52213): client disconnected
2021-11-22 00:24:54,739   INFO       server.py    [WinError 10054] Удаленный хост принудительно разорвал существующее подключение
2021-11-22 00:24:55,152   INFO       server.py    ('127.0.0.1', 52215): client connection established
2021-11-22 00:24:56,161   DEBUG      server.py    Function: handle_message, args: (<__main__.Server object at 0x0000022F15852350>, {'action': 'presence', 'time': 1637529895.2800393, 'user': {'account_name': 'Guest', 'status': 'online'}, 'type': 'status'}, <socket.socket fd=296, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 52215)>), kwargs: {}, called from function: set_up
2021-11-22 00:24:56,161   INFO       server.py    ('127.0.0.1', 52215): the message from the client is being handled
2021-11-22 00:24:56,161   INFO       server.py    ('127.0.0.1', 52215): name 'Guest' status 'online'
2021-11-22 00:24:56,162   INFO       server.py    ('127.0.0.1', 52215): name 'Guest' added into clients_usernames
2021-11-22 00:26:39,713   INFO       server.py    ('127.0.0.1', 52217): client connection established
2021-11-22 00:26:39,714   INFO       server.py    ('127.0.0.1', 52215): client disconnected
2021-11-22 00:26:39,714   INFO       server.py    [WinError 10054] Удаленный хост принудительно разорвал существующее подключение
2021-11-22 00:26:40,718   DEBUG      server.py    Function: handle_message, args: (<__main__.Server object at 0x0000022F15852350>, {'action': 'presence', 'time': 1637530000.0482123, 'user': {'account_name': 'Guest', 'status': 'online'}, 'type': 'status'}, <socket.socket fd=292, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 52217)>), kwargs: {}, called from function: set_up
2021-11-22 00:26:40,718   INFO       server.py    ('127.0.0.1', 52217): the message from the client is being handled
2021-11-22 00:26:40,719   INFO       server.py    ('127.0.0.1', 52217): name 'Guest' status 'online'
2021-11-22 00:26:40,719   INFO       server.py    ('127.0.0.1', 52217): name 'Guest' added into clients_usernames
2021-11-22 00:27:56,359   INFO       server.py    ('127.0.0.1', 52217): client disconnected
2021-11-22 00:27:56,359   INFO       server.py    [WinError 10054] Удаленный хост принудительно разорвал существующее подключение
2021-11-22 00:27:56,602   INFO       server.py    ('127.0.0.1', 52220): client connection established
2021-11-22 00:27:57,608   DEBUG      server.py    Function: handle_message, args: (<__main__.Server object at 0x0000022F15852350>, {'action': 'presence', 'time': 1637530076.657138, 'user': {'account_name': 'Guest', 'status': 'online'}, 'type': 'status'}, <socket.socket fd=396, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 52220)>), kwargs: {}, called from function: set_up
2021-11-22 00:27:57,608   INFO       server.py    ('127.0.0.1', 52220): the message from the client is being handled
2021-11-22 00:27:57,608   INFO       server.py    ('127.0.0.1', 52220): name 'Guest' status 'online'
2021-11-22 00:27:57,609   INFO       server.py    ('127.0.0.1', 52220): name 'Guest' added into clients_usernames
2021-11-22 00:29:28,252   INFO       server.py    ('127.0.0.1', 52220): client disconnected
2021-11-22 00:29:28,252   INFO       server.py    [WinError 10054] Удаленный хост принудительно разорвал существующее подключение
2021-11-22 00:30:04,906   INFO       server.py    ('127.0.0.1', 52227): client connection established
2021-11-22 00:30:05,916   DEBUG      server.py    Function: handle_message, args: (<__main__.Server object at 0x0000022F15852350>, {'action': 'presence', 'time': 1637530204.9342616, 'user': {'account_name': 'Guest', 'status': 'online'}, 'type': 'status'}, <socket.socket fd=352, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 52227)>), kwargs: {}, called from function: set_up
2021-11-22 00:30:05,916   INFO       server.py    ('127.0.0.1', 52227): the message from the client is being handled
2021-11-22 00:30:05,916   INFO       server.py    ('127.0.0.1', 52227): name 'Guest' status 'online'
2021-11-22 00:30:05,916   INFO       server.py    ('127.0.0.1', 52227): name 'Guest' added into clients_usernames
2021-11-22 00:31:56,414   INFO       server.py    ('127.0.0.1', 52232): client connection established
2021-11-22 00:31:56,414   INFO       server.py    ('127.0.0.1', 52227): client disconnected
2021-11-22 00:31:56,415   INFO       server.py    [WinError 10054] Удаленный хост принудительно разорвал существующее подключение
2021-11-22 00:31:57,426   DEBUG      server.py    Function: handle_message, args: (<__main__.Server object at 0x0000022F15852350>, {'action': 'presence', 'time': 1637530316.479231, 'user': {'account_name': 'Guest', 'status': 'online'}, 'type': 'status'}, <socket.socket fd=300, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 52232)>), kwargs: {}, called from function: set_up
2021-11-22 00:31:57,426   INFO       server.py    ('127.0.0.1', 52232): the message from the client is being handled
2021-11-22 00:31:57,426   INFO       server.py    ('127.0.0.1', 52232): name 'Guest' status 'online'
2021-11-22 00:31:57,426   INFO       server.py    ('127.0.0.1', 52232): name 'Guest' added into clients_usernames
2021-11-22 00:50:15,859   INFO       server.py    server started at 7777 and listened all ip
2021-11-22 00:53:16,258   INFO       server.py    ('127.0.0.1', 52269): client connection established
2021-11-22 00:53:17,309   DEBUG      server.py    Function: handle_message, args: (<__main__.Server object at 0x0000014431AABC40>, {'action': 'presence', 'time': 1637531596.2864256, 'user': {'account_name': 'Guest', 'status': 'online'}, 'type': 'status'}, <socket.socket fd=292, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 52269)>), kwargs: {}, called from function: set_up
2021-11-22 00:53:17,309   INFO       server.py    ('127.0.0.1', 52269): the message from the client is being handled
2021-11-22 00:53:17,309   INFO       server.py    ('127.0.0.1', 52269): name 'Guest' status 'online'
2021-11-22 00:53:17,310   INFO       server.py    ('127.0.0.1', 52269): name 'Guest' added into clients_usernames
2021-11-22 00:53:28,414   INFO       server.py    ('127.0.0.1', 52269): client disconnected
2021-11-22 00:53:28,414   INFO       server.py    [WinError 10054] Удаленный хост принудительно разорвал существующее подключение
2021-11-22 00:53:28,739   INFO       server.py    ('127.0.0.1', 52271): client connection established
2021-11-22 00:53:29,755   DEBUG      server.py    Function: handle_message, args: (<__main__.Server object at 0x0000014431AABC40>, {'action': 'presence', 'time': 1637531608.8604019, 'user': {'account_name': 'Guest', 'status': 'online'}, 'type': 'status'}, <socket.socket fd=316, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 52271)>), kwargs: {}, called from function: set_up
2021-11-22 00:53:29,756   INFO       server.py    ('127.0.0.1', 52271): the message from the client is being handled
2021-11-22 00:53:29,756   INFO       server.py    ('127.0.0.1', 52271): name 'Guest' status 'online'
2021-11-22 00:53:29,757   INFO       server.py    ('127.0.0.1', 52271): name 'Guest' added into clients_usernames
2021-11-22 00:53:48,926   INFO       server.py    ('127.0.0.1', 52271): client disconnected
2021-11-22 00:53:48,926   INFO       server.py    [WinError 10054] Удаленный хост принудительно разорвал существующее подключение
2021-11-22 00:54:02,841   INFO       server.py    ('127.0.0.1', 52273): client connection established
2021-11-22 00:54:03,852   DEBUG      server.py    Function: handle_message, args: (<__main__.Server object at 0x0000014431AABC40>, {'action': 'presence', 'time': 1637531642.9247348, 'user': {'account_name': 'Guest', 'status': 'online'}, 'type': 'status'}, <socket.socket fd=312, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 52273)>), kwargs: {}, called from function: set_up
2021-11-22 00:54:03,853   INFO       server.py    ('127.0.0.1', 52273): the message from the client is being handled
2021-11-22 00:54:03,853   INFO       server.py    ('127.0.0.1', 52273): name 'Guest' status 'online'
2021-11-22 00:54:03,853   INFO       server.py    ('127.0.0.1', 52273): name 'Guest' added into clients_usernames
2021-11-22 00:54:18,012   INFO       server.py    ('127.0.0.1', 52273): client disconnected
2021-11-22 00:54:18,012   INFO       server.py    [WinError 10054] Удаленный хост принудительно разорвал существующее подключение
2021-11-22 00:54:18,661   INFO       server.py    ('127.0.0.1', 52276): client connection established
2021-11-22 00:54:19,670   DEBUG      server.py    Function: handle_message, args: (<__main__.Server object at 0x0000014431AABC40>, {'action': 'presence', 'time': 1637531658.6981072, 'user': {'account_name': 'Guest', 'status': 'online'}, 'type': 'status'}, <socket.socket fd=316, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 52276)>), kwargs: {}, called from function: set_up
2021-11-22 00:54:19,670   INFO       server.py    ('127.0.0.1', 52276): the message from the client is being handled
2021-11-22 00:54:19,670   INFO       server.py    ('127.0.0.1', 52276): name 'Guest' status 'online'
2021-11-22 00:54:19,670   INFO       server.py    ('127.0.0.1', 52276): name 'Guest' added into clients_usernames
2021-11-22 01:17:59,425   INFO       server.py    ('127.0.0.1', 52276): client disconnected
2021-11-22 01:17:59,425   INFO       server.py    [WinError 10054] Удаленный хост принудительно разорвал существующее подключение
2021-11-22 01:18:10,818   INFO       server.py    server started at 7777 and listened all ip
2021-11-22 01:18:16,708   INFO       server.py    ('127.0.0.1', 52332): client connection established
2021-11-22 01:18:17,746   DEBUG      server.py    Function: handle_message, args: (<__main__.Server object at 0x000001CC6487BC40>, {'action': 'presence', 'time': 1637533096.736294, 'user': {'account_name': 'Guest', 'status': 'online'}, 'type': 'status'}, <socket.socket fd=340, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 52332)>), kwargs: {}, called from function: set_up
2021-11-22 01:18:17,746   INFO       server.py    ('127.0.0.1', 52332): the message from the client is being handled
2021-11-22 01:18:17,747   INFO       server.py    ('127.0.0.1', 52332): name 'Guest' status 'online'
2021-11-22 01:18:17,747   INFO       server.py    ('127.0.0.1', 52332): name 'Guest' added into clients_usernames
2021-11-22 01:20:19,860   INFO       server.py    ('127.0.0.1', 52332): client disconnected
2021-11-22 01:20:19,860   INFO       server.py    [WinError 10054] Удаленный хост принудительно разорвал существующее подключение
2021-11-22 01:22:08,686   INFO       server.py    server started at 8888 and listened all ip
2021-11-22 01:22:15,269   INFO       server.py    ('127.0.0.1', 52339): client connection established
2021-11-22 01:22:16,299   DEBUG      server.py    Function: handle_message, args: (<__main__.Server object at 0x000001F0C9CCF400>, {'action': 'presence', 'time': 1637533335.2953107, 'user': {'account_name': 'Guest', 'status': 'online'}, 'type': 'status'}, <socket.socket fd=352, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 8888), raddr=('127.0.0.1', 52339)>), kwargs: {}, called from function: set_up
2021-11-22 01:22:16,299   INFO       server.py    ('127.0.0.1', 52339): the message from the client is being handled
2021-11-22 01:22:16,300   INFO       server.py    ('127.0.0.1', 52339): name 'Guest' status 'online'
2021-11-22 01:22:16,300   INFO       server.py    ('127.0.0.1', 52339): name 'Guest' added into clients_usernames
2021-11-22 01:22:24,356   INFO       server.py    ('127.0.0.1', 52339): client disconnected
2021-11-22 01:22:24,356   INFO       server.py    [WinError 10054] Удаленный хост принудительно разорвал существующее подключение
2021-11-22 01:22:34,032   INFO       server.py    ('127.0.0.1', 52341): client connection established
2021-11-22 01:22:34,041   INFO       server.py    ('127.0.0.1', 52342): client connection established
2021-11-22 01:22:34,065   INFO       server.py    ('127.0.0.1', 52343): client connection established
2021-11-22 01:22:35,081   DEBUG      server.py    Function: handle_message, args: (<__main__.Server object at 0x000001F0C9CCF400>, {'action': 'presence', 'time': 1637533354.0717766, 'user': {'account_name': '1', 'status': 'online'}, 'type': 'status'}, <socket.socket fd=468, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 8888), raddr=('127.0.0.1', 52341)>), kwargs: {}, called from function: set_up
2021-11-22 01:22:35,081   INFO       server.py    ('127.0.0.1', 52341): the message from the client is being handled
2021-11-22 01:22:35,081   INFO       server.py    ('127.0.0.1', 52341): name '1' status 'online'
2021-11-22 01:22:35,082   INFO       server.py    ('127.0.0.1', 52341): name '1' added into clients_usernames
2021-11-22 01:22:35,084   DEBUG      server.py    Function: handle_message, args: (<__main__.Server object at 0x000001F0C9CCF400>, {'action': 'presence', 'time': 1637533354.0877676, 'user': {'account_name': '2', 'status': 'online'}, 'type': 'status'}, <socket.socket fd=456, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 8888), raddr=('127.0.0.1', 52342)>), kwargs: {}, called from function: set_up
2021-11-22 01:22:35,085   INFO       server.py    ('127.0.0.1', 52342): the message from the client is being handled
2021-11-22 01:22:35,085   INFO       server.py    ('127.0.0.1', 52342): name '2' status 'online'
2021-11-22 01:22:35,086   INFO       server.py    ('127.0.0.1', 52342): name '2' added into clients_usernames
2021-11-22 01:22:35,088   DEBUG      server.py    Function: handle_message, args: (<__main__.Server object at 0x000001F0C9CCF400>, {'action': 'presence', 'time': 1637533354.1107533, 'user': {'account_name': '3', 'status': 'online'}, 'type': 'status'}, <socket.socket fd=348, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 8888), raddr=('127.0.0.1', 52343)>), kwargs: {}, called from function: set_up
2021-11-22 01:22:35,088   INFO       server.py    ('127.0.0.1', 52343): the message from the client is being handled
2021-11-22 01:22:35,090   INFO       server.py    ('127.0.0.1', 52343): name '3' status 'online'
2021-11-22 01:22:35,091   INFO       server.py    ('127.0.0.1', 52343): name '3' added into clients_usernames
2021-11-22 01:22:50,219   INFO       server.py    ('127.0.0.1', 52342): client disconnected
2021-11-22 01:22:50,219   INFO       server.py    [WinError 10054] Удаленный хост принудительно разорвал существующее подключение
2021-11-22 01:22:57,417   INFO       server.py    server started at 8888 and listened all ip
2021-11-22 01:22:57,421   INFO       server.py    ('127.0.0.1', 52347): client connection established
2021-11-22 01:22:57,472   INFO       server.py    ('127.0.0.1', 52348): client connection established
2021-11-22 01:22:57,501   DEBUG      server.py    Function: handle_message, args: (<__main__.Server object at 0x000001D358C8F3D0>, {'action': 'presence', 'time': 1637533377.4659605, 'user': {'account_name': '1', 'status': 'online'}, 'type': 'status'}, <socket.socket fd=312, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 8888), raddr=('127.0.0.1', 52347)>), kwargs: {}, called from function: set_up
2021-11-22 01:22:57,501   INFO       server.py    ('127.0.0.1', 52347): the message from the client is being handled
2021-11-22 01:22:57,501   INFO       server.py    ('127.0.0.1', 52347): name '1' status 'online'
2021-11-22 01:22:57,501   INFO       server.py    ('127.0.0.1', 52347): name '1' added into clients_usernames
2021-11-22 01:22:57,921   INFO       server.py    ('127.0.0.1', 52346): client connection established
2021-11-22 01:22:57,923   DEBUG      server.py    Function: handle_message, args: (<__main__.Server object at 0x000001D358C8F3D0>, {'action': 'presence', 'time': 1637533377.5091994, 'user': {'account_name': '3', 'status': 'online'}, 'type': 'status'}, <socket.socket fd=300, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 8888), raddr=('127.0.0.1', 52348)>), kwargs: {}, called from function: set_up
2021-11-22 01:22:57,923   INFO       server.py    ('127.0.0.1', 52348): the message from the client is being handled
2021-11-22 01:22:57,925   INFO       server.py    ('127.0.0.1', 52348): name '3' status 'online'
2021-11-22 01:22:57,926   INFO       server.py    ('127.0.0.1', 52348): name '3' added into clients_usernames
2021-11-22 01:22:58,936   DEBUG      server.py    Function: handle_message, args: (<__main__.Server object at 0x000001D358C8F3D0>, {'action': 'presence', 'time': 1637533377.95738, 'user': {'account_name': '2', 'status': 'online'}, 'type': 'status'}, <socket.socket fd=436, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 8888), raddr=('127.0.0.1', 52346)>), kwargs: {}, called from function: set_up
2021-11-22 01:22:58,937   INFO       server.py    ('127.0.0.1', 52346): the message from the client is being handled
2021-11-22 01:22:58,937   INFO       server.py    ('127.0.0.1', 52346): name '2' status 'online'
2021-11-22 01:22:58,937   INFO       server.py    ('127.0.0.1', 52346): name '2' added into clients_usernames
2021-11-22 01:23:28,194   DEBUG      server.py    Function: handle_message, args: (<__main__.Server object at 0x000001D358C8F3D0>, {'action': 'message', 'time': 1637533407.7776723, 'to': '3', 'from': '1', 'message_text': 'hello'}, <socket.socket fd=300, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 8888), raddr=('127.0.0.1', 52348)>), kwargs: {}, called from function: set_up
2021-11-22 01:23:28,194   INFO       server.py    ('127.0.0.1', 52348): the message from the client is being handled
2021-11-22 01:23:28,194   INFO       server.py    message: hello from: 3 to: 1 appended into messages_list
2021-11-22 01:23:34,245   INFO       server.py    ('127.0.0.1', 52347): client disconnected
2021-11-22 01:23:34,245   INFO       server.py    [WinError 10054] Удаленный хост принудительно разорвал существующее подключение
2021-11-22 01:23:36,263   INFO       server.py    ('127.0.0.1', 52348): client disconnected
2021-11-22 01:23:36,264   INFO       server.py    [WinError 10054] Удаленный хост принудительно разорвал существующее подключение
