2021-09-16 23:18:24,427   INFO       server.py    server started at 7777 and listened all ip
2021-09-16 23:19:17,164   INFO       server.py    client connected: ('127.0.0.1', 51241)
2021-09-16 23:19:17,164   DEBUG      server.py    message reseived {'action': 'presence', 'time': 1631823557.16467, 'user': {'account_name': 'Катя', 'status': 'online'}, 'type': 'status'}
2021-09-16 23:19:17,180   DEBUG      server.py    Function: handle_message, args: ({'action': 'presence', 'time': 1631823557.16467, 'user': {'account_name': 'Катя', 'status': 'online'}, 'type': 'status'},), kwargs: {}, called from function: main
2021-09-16 23:19:17,180   DEBUG      server.py    the message from the client is being handled
2021-09-16 23:19:17,180   DEBUG      server.py    a response to the client is generated: {'response': 402, 'error': 'no account with that name'}
2021-09-16 23:19:17,180   DEBUG      server.py    responce was sent to the client
2021-09-16 23:19:17,180   DEBUG      server.py    client connection closed
2021-09-16 23:19:33,387   INFO       server.py    client connected: ('127.0.0.1', 51242)
2021-09-16 23:19:33,387   DEBUG      server.py    message reseived {'action': 'presence', 'time': 1631823573.3874164, 'user': {'account_name': 'Guest', 'status': 'online'}, 'type': 'status'}
2021-09-16 23:19:33,387   DEBUG      server.py    Function: handle_message, args: ({'action': 'presence', 'time': 1631823573.3874164, 'user': {'account_name': 'Guest', 'status': 'online'}, 'type': 'status'},), kwargs: {}, called from function: main
2021-09-16 23:19:33,387   DEBUG      server.py    the message from the client is being handled
2021-09-16 23:19:33,387   INFO       server.py    Guest: online
2021-09-16 23:19:33,387   DEBUG      server.py    a response to the client is generated: {'response': 200}
2021-09-16 23:19:33,387   DEBUG      server.py    responce was sent to the client
2021-09-16 23:19:33,387   DEBUG      server.py    client connection closed
2021-09-16 23:19:43,204   INFO       server.py    client connected: ('127.0.0.1', 51243)
2021-09-16 23:19:43,204   DEBUG      server.py    message reseived {'action': 'presence', 'time': 1631823583.2043972, 'user': {'account_name': 'Guest', 'status': 'online'}, 'type': 'status'}
2021-09-16 23:19:43,205   DEBUG      server.py    Function: handle_message, args: ({'action': 'presence', 'time': 1631823583.2043972, 'user': {'account_name': 'Guest', 'status': 'online'}, 'type': 'status'},), kwargs: {}, called from function: main
2021-09-16 23:19:43,205   DEBUG      server.py    the message from the client is being handled
2021-09-16 23:19:43,205   INFO       server.py    Guest: online
2021-09-16 23:19:43,205   DEBUG      server.py    a response to the client is generated: {'response': 200}
2021-09-16 23:19:43,205   DEBUG      server.py    responce was sent to the client
2021-09-16 23:19:43,206   DEBUG      server.py    client connection closed
2021-09-16 23:19:50,334   INFO       server.py    client connected: ('127.0.0.1', 51244)
2021-09-16 23:19:50,334   DEBUG      server.py    message reseived {'action': 'presence', 'time': 1631823590.3347886, 'user': {'account_name': 'user', 'status': 'online'}, 'type': 'status'}
2021-09-16 23:19:50,350   DEBUG      server.py    Function: handle_message, args: ({'action': 'presence', 'time': 1631823590.3347886, 'user': {'account_name': 'user', 'status': 'online'}, 'type': 'status'},), kwargs: {}, called from function: main
2021-09-16 23:19:50,350   DEBUG      server.py    the message from the client is being handled
2021-09-16 23:19:50,350   DEBUG      server.py    a response to the client is generated: {'response': 402, 'error': 'no account with that name'}
2021-09-16 23:19:50,350   DEBUG      server.py    responce was sent to the client
2021-09-16 23:19:50,350   DEBUG      server.py    client connection closed
2021-09-16 23:20:28,867   INFO       server.py    client connected: ('127.0.0.1', 51246)
2021-09-16 23:20:28,867   DEBUG      server.py    message reseived {'action': 'presence', 'time': 1631823628.8671036, 'user': {'account_name': 'Guest', 'status': 'online'}, 'type': 'status'}
2021-09-16 23:20:28,867   DEBUG      server.py    Function: handle_message, args: ({'action': 'presence', 'time': 1631823628.8671036, 'user': {'account_name': 'Guest', 'status': 'online'}, 'type': 'status'},), kwargs: {}, called from function: main
2021-09-16 23:20:28,867   DEBUG      server.py    the message from the client is being handled
2021-09-16 23:20:28,867   INFO       server.py    Guest: online
2021-09-16 23:20:28,867   DEBUG      server.py    a response to the client is generated: {'response': 200}
2021-09-16 23:20:28,867   DEBUG      server.py    responce was sent to the client
2021-09-16 23:20:28,867   DEBUG      server.py    client connection closed
2021-09-16 23:27:18,087   INFO       server.py    server started at 7777 and listened all ip
2021-09-16 23:27:26,681   INFO       server.py    client connected: ('127.0.0.1', 63980)
2021-09-16 23:27:26,681   DEBUG      server.py    message reseived {'action': 'presence', 'time': 1631824046.6811392, 'user': {'account_name': 'Guest', 'status': 'online'}, 'type': 'status'}
2021-09-16 23:27:26,712   DEBUG      server.py    Function: handle_message, args: ({'action': 'presence', 'time': 1631824046.6811392, 'user': {'account_name': 'Guest', 'status': 'online'}, 'type': 'status'},), kwargs: {}, called from function: main
2021-09-16 23:27:26,712   DEBUG      server.py    the message from the client is being handled
2021-09-16 23:27:26,712   INFO       server.py    Guest: online
2021-09-16 23:27:26,712   DEBUG      server.py    a response to the client is generated: {'response': 200}
2021-09-16 23:27:26,712   DEBUG      server.py    responce was sent to the client
2021-09-16 23:27:26,712   DEBUG      server.py    client connection closed
2021-09-16 23:40:02,929   DEBUG      server.py    Function: server_arg_parser, args: (), kwargs: {}, called from function: main
2021-09-16 23:40:19,505   DEBUG      server.py    Function: server_arg_parser, args: (), kwargs: {}, called from function: main
2021-09-16 23:40:19,520   INFO       server.py    server started at 7777 and listened all ip
2021-09-16 23:40:26,614   INFO       server.py    client connected: ('127.0.0.1', 62041)
2021-09-16 23:40:26,614   DEBUG      server.py    message reseived {'action': 'presence', 'time': 1631824826.6145632, 'user': {'account_name': 'Guest', 'status': 'online'}, 'type': 'status'}
2021-09-16 23:40:26,614   DEBUG      server.py    Function: handle_message, args: ({'action': 'presence', 'time': 1631824826.6145632, 'user': {'account_name': 'Guest', 'status': 'online'}, 'type': 'status'},), kwargs: {}, called from function: main
2021-09-16 23:40:26,614   DEBUG      server.py    the message from the client is being handled
2021-09-16 23:40:26,614   INFO       server.py    Guest: online
2021-09-16 23:40:26,614   DEBUG      server.py    a response to the client is generated: {'response': 200}
2021-09-16 23:40:26,614   DEBUG      server.py    responce was sent to the client
2021-09-16 23:40:26,614   DEBUG      server.py    client connection closed
2021-09-16 23:40:55,755   DEBUG      server.py    Function: server_arg_parser, args: (), kwargs: {}, called from function: main
2021-09-16 23:40:55,771   INFO       server.py    server started at 7777 and listened ip 127.0.0.1
2021-09-16 23:41:12,775   DEBUG      server.py    Function: server_arg_parser, args: (), kwargs: {}, called from function: main
2021-09-16 23:41:12,791   INFO       server.py    server started at 7777 and listened all ip
2021-09-16 23:41:43,095   DEBUG      server.py    Function: server_arg_parser, args: (), kwargs: {}, called from function: main
2021-09-16 23:41:43,108   CRITICAL   server.py    wrong port number: 1000
2021-09-16 23:41:51,265   DEBUG      server.py    Function: server_arg_parser, args: (), kwargs: {}, called from function: main
2021-09-16 23:41:51,278   CRITICAL   server.py    wrong port number: 1000
2021-09-16 23:41:54,219   DEBUG      server.py    Function: server_arg_parser, args: (), kwargs: {}, called from function: main
2021-09-16 23:41:54,234   CRITICAL   server.py    wrong port number: 100
2021-09-16 23:42:03,773   DEBUG      server.py    Function: server_arg_parser, args: (), kwargs: {}, called from function: main
