2021-09-13 21:22:10,297   INFO       server.py    server started at 7777 and listened all ip
2021-09-13 21:23:14,365   INFO       server.py    client connected: ('127.0.0.1', 54770)
2021-09-13 21:23:14,365   DEBUG      server.py    message reseived {'action': 'presence', 'time': 1631557394.3655474, 'user': {'account_name': 'Guest', 'status': 'online'}, 'type': 'status'}
2021-09-13 21:23:14,366   DEBUG      server.py    the message from the client is being handled
2021-09-13 21:23:14,366   INFO       server.py    a response to the client is generated: {'response': 200}
2021-09-13 21:23:14,366   DEBUG      server.py    responce was sent to the client
2021-09-13 21:23:14,366   DEBUG      server.py    client connection closed
2021-09-13 21:23:22,580   INFO       server.py    client connected: ('127.0.0.1', 54771)
2021-09-13 21:23:22,582   DEBUG      server.py    message reseived {'action': 'presence', 'time': 1631557402.5827425, 'user': {'account_name': 'Guest', 'status': 'online'}, 'type': 'status'}
2021-09-13 21:23:22,582   DEBUG      server.py    the message from the client is being handled
2021-09-13 21:23:22,582   INFO       server.py    a response to the client is generated: {'response': 200}
2021-09-13 21:23:22,582   DEBUG      server.py    responce was sent to the client
2021-09-13 21:23:22,582   DEBUG      server.py    client connection closed
2021-09-13 21:23:31,854   INFO       server.py    server started at 7777 and listened all ip
2021-09-13 21:23:38,587   INFO       server.py    client connected: ('127.0.0.1', 54773)
2021-09-13 21:23:38,587   DEBUG      server.py    message reseived {'action': 'presence', 'time': 1631557418.587937, 'user': {'account_name': 'Guest', 'status': 'online'}, 'type': 'status'}
2021-09-13 21:23:38,587   DEBUG      server.py    the message from the client is being handled
2021-09-13 21:23:38,588   INFO       server.py    a response to the client is generated: {'response': 200}
2021-09-13 21:23:38,588   DEBUG      server.py    responce was sent to the client
2021-09-13 21:23:38,588   DEBUG      server.py    client connection closed
2021-09-13 21:24:20,435   INFO       server.py    server started at 7777 and listened all ip
2021-09-13 21:24:22,244   INFO       server.py    server started at 7777 and listened all ip
2021-09-13 21:24:32,291   INFO       server.py    client connected: ('127.0.0.1', 54780)
2021-09-13 21:24:32,293   DEBUG      server.py    message reseived {'action': 'presence', 'time': 1631557472.2925878, 'user': {'account_name': 'Guest', 'status': 'online'}, 'type': 'status'}
2021-09-13 21:24:32,293   DEBUG      server.py    the message from the client is being handled
2021-09-13 21:24:32,293   INFO       server.py    a response to the client is generated: {'response': 200}
2021-09-13 21:24:32,293   DEBUG      server.py    responce was sent to the client
2021-09-13 21:24:32,294   DEBUG      server.py    client connection closed
2021-09-13 21:27:10,019   INFO       server.py    client connected: ('127.0.0.1', 64648)
2021-09-13 21:27:10,019   DEBUG      server.py    message reseived {'action': 'presence', 'time': 1631557630.0195405, 'user': {'account_name': 'Катя', 'status': 'online'}, 'type': 'status'}
2021-09-13 21:27:10,019   DEBUG      server.py    the message from the client is being handled
2021-09-13 21:27:10,020   INFO       server.py    a response to the client is generated: {'response': 402, 'error': 'no account with that name'}
2021-09-13 21:27:10,020   DEBUG      server.py    responce was sent to the client
2021-09-13 21:27:10,020   DEBUG      server.py    client connection closed
2021-09-13 21:28:17,495   INFO       server.py    client connected: ('127.0.0.1', 64650)
2021-09-13 21:28:17,495   DEBUG      server.py    message reseived {'action': 'presence', 'time': 1631557697.4953249, 'user': {'account_name': 'Катя', 'status': 'online'}, 'type': 'status'}
2021-09-13 21:28:17,495   DEBUG      server.py    the message from the client is being handled
2021-09-13 21:28:17,495   INFO       server.py    a response to the client is generated: {'response': 402, 'error': 'no account with that name'}
2021-09-13 21:28:17,496   DEBUG      server.py    responce was sent to the client
2021-09-13 21:28:17,496   DEBUG      server.py    client connection closed
2021-09-13 21:32:48,485   INFO       server.py    client connected: ('127.0.0.1', 52690)
2021-09-13 21:32:48,486   DEBUG      server.py    message reseived {'action': 'presence', 'time': 1631557968.4867253, 'user': {'account_name': 'Катя', 'status': 'online'}, 'type': 'status'}
2021-09-13 21:32:48,486   DEBUG      server.py    the message from the client is being handled
2021-09-13 21:32:48,486   INFO       server.py    a response to the client is generated: {'response': 402, 'error': 'no account with that name'}
2021-09-13 21:32:48,487   DEBUG      server.py    responce was sent to the client
2021-09-13 21:32:48,487   DEBUG      server.py    client connection closed
2021-09-13 21:47:09,219   INFO       server.py    client connected: ('127.0.0.1', 55255)
2021-09-13 21:47:09,259   DEBUG      server.py    message reseived {'action': 'presence', 'time': 1631558829.259145, 'user': {'account_name': 'Катя', 'status': 'online'}, 'type': 'status'}
2021-09-13 21:47:09,260   DEBUG      server.py    the message from the client is being handled
2021-09-13 21:47:09,260   INFO       server.py    a response to the client is generated: {'response': 402, 'error': 'no account with that name'}
2021-09-13 21:47:09,260   DEBUG      server.py    responce was sent to the client
2021-09-13 21:47:09,261   DEBUG      server.py    client connection closed
2021-09-13 21:48:39,597   INFO       server.py    client connected: ('127.0.0.1', 49258)
2021-09-13 21:48:39,637   DEBUG      server.py    message reseived {'action': 'presence', 'time': 1631558919.6373885, 'user': {'account_name': 'Катя', 'status': 'online'}, 'type': 'status'}
2021-09-13 21:48:39,638   DEBUG      server.py    the message from the client is being handled
2021-09-13 21:48:39,638   INFO       server.py    a response to the client is generated: {'response': 402, 'error': 'no account with that name'}
2021-09-13 21:48:39,638   DEBUG      server.py    responce was sent to the client
2021-09-13 21:48:39,638   DEBUG      server.py    client connection closed
2021-09-13 21:54:37,559   INFO       server.py    client connected: ('127.0.0.1', 61160)
2021-09-13 21:54:37,599   DEBUG      server.py    message reseived {'action': 'presence', 'time': 1631559277.599818, 'user': {'account_name': 'Катя', 'status': 'online'}, 'type': 'status'}
2021-09-13 21:54:37,599   DEBUG      server.py    the message from the client is being handled
2021-09-13 21:54:37,600   INFO       server.py    a response to the client is generated: {'response': 402, 'error': 'no account with that name'}
2021-09-13 21:54:37,600   DEBUG      server.py    responce was sent to the client
2021-09-13 21:54:37,600   DEBUG      server.py    client connection closed
2021-09-13 21:54:43,034   INFO       server.py    client connected: ('127.0.0.1', 61161)
2021-09-13 21:54:43,113   DEBUG      server.py    message reseived {'action': 'presence', 'time': 1631559283.1130722, 'user': {'account_name': 'Катя', 'status': 'online'}, 'type': 'status'}
2021-09-13 21:54:43,114   DEBUG      server.py    the message from the client is being handled
2021-09-13 21:54:43,114   INFO       server.py    a response to the client is generated: {'response': 402, 'error': 'no account with that name'}
2021-09-13 21:54:43,114   DEBUG      server.py    responce was sent to the client
2021-09-13 21:54:43,114   DEBUG      server.py    client connection closed
2021-09-13 21:54:53,415   INFO       server.py    client connected: ('127.0.0.1', 61162)
2021-09-13 21:54:53,454   DEBUG      server.py    message reseived {'action': 'presence', 'time': 1631559293.454821, 'user': {'account_name': 'Катя', 'status': 'online'}, 'type': 'status'}
2021-09-13 21:54:53,454   DEBUG      server.py    the message from the client is being handled
2021-09-13 21:54:53,454   INFO       server.py    a response to the client is generated: {'response': 402, 'error': 'no account with that name'}
2021-09-13 21:54:53,455   DEBUG      server.py    responce was sent to the client
2021-09-13 21:54:53,455   DEBUG      server.py    client connection closed
2021-09-13 21:59:54,328   INFO       server.py    client connected: ('127.0.0.1', 58693)
2021-09-13 21:59:54,379   DEBUG      server.py    message reseived {'action': 'presence', 'time': 1631559594.3797193, 'user': {'account_name': 'Катя', 'status': 'online'}, 'type': 'status'}
2021-09-13 21:59:54,379   DEBUG      server.py    the message from the client is being handled
2021-09-13 21:59:54,379   INFO       server.py    a response to the client is generated: {'response': 402, 'error': 'no account with that name'}
2021-09-13 21:59:54,380   DEBUG      server.py    responce was sent to the client
2021-09-13 21:59:54,380   DEBUG      server.py    client connection closed
2021-09-13 22:14:34,360   INFO       server.py    server started at 7777 and listened all ip
2021-09-13 22:15:08,194   INFO       server.py    client connected: ('127.0.0.1', 61772)
2021-09-13 22:15:08,225   DEBUG      server.py    message reseived {'action': 'presence', 'time': 1631560508.2257044, 'user': {'account_name': 'Катя', 'status': 'online'}, 'type': 'status'}
2021-09-13 22:15:08,241   DEBUG      server.py    the message from the client is being handled
2021-09-13 22:15:08,241   INFO       server.py    a response to the client is generated: {'response': 402, 'error': 'no account with that name'}
2021-09-13 22:15:08,241   DEBUG      server.py    responce was sent to the client
2021-09-13 22:15:08,241   DEBUG      server.py    client connection closed
2021-09-13 22:16:49,822   INFO       server.py    client connected: ('127.0.0.1', 53280)
2021-09-13 22:16:49,846   DEBUG      server.py    message reseived {'action': 'presence', 'time': 1631560609.8458164, 'user': {'account_name': 'Катя', 'status': 'online'}, 'type': 'status'}
2021-09-13 22:16:49,847   DEBUG      server.py    the message from the client is being handled
2021-09-13 22:16:49,847   INFO       server.py    a response to the client is generated: {'response': 402, 'error': 'no account with that name'}
2021-09-13 22:16:49,848   DEBUG      server.py    responce was sent to the client
2021-09-13 22:16:49,848   DEBUG      server.py    client connection closed
2021-09-13 22:18:33,243   INFO       server.py    client connected: ('127.0.0.1', 56669)
2021-09-13 22:18:33,274   DEBUG      server.py    message reseived {'action': 'presence', 'time': 1631560713.2743673, 'user': {'account_name': 'Катя', 'status': 'online'}, 'type': 'status'}
2021-09-13 22:18:33,274   DEBUG      server.py    the message from the client is being handled
2021-09-13 22:18:33,274   INFO       server.py    a response to the client is generated: {'response': 402, 'error': 'no account with that name'}
2021-09-13 22:18:33,274   DEBUG      server.py    responce was sent to the client
2021-09-13 22:18:33,274   DEBUG      server.py    client connection closed
2021-09-13 22:18:49,986   INFO       server.py    client connected: ('127.0.0.1', 56670)
2021-09-13 22:18:50,011   DEBUG      server.py    message reseived {'action': 'presence', 'time': 1631560730.0113804, 'user': {'account_name': 'Катя', 'status': 'online'}, 'type': 'status'}
2021-09-13 22:18:50,013   DEBUG      server.py    the message from the client is being handled
2021-09-13 22:18:50,013   INFO       server.py    a response to the client is generated: {'response': 402, 'error': 'no account with that name'}
2021-09-13 22:18:50,013   DEBUG      server.py    responce was sent to the client
2021-09-13 22:18:50,013   DEBUG      server.py    client connection closed
2021-09-13 22:19:28,403   INFO       server.py    client connected: ('127.0.0.1', 56671)
2021-09-13 22:19:28,434   DEBUG      server.py    message reseived {'action': 'presence', 'time': 1631560768.434914, 'user': {'account_name': 'Катя', 'status': 'online'}, 'type': 'status'}
2021-09-13 22:19:28,434   DEBUG      server.py    the message from the client is being handled
2021-09-13 22:19:28,434   INFO       server.py    a response to the client is generated: {'response': 402, 'error': 'no account with that name'}
2021-09-13 22:19:28,434   DEBUG      server.py    responce was sent to the client
2021-09-13 22:19:28,434   DEBUG      server.py    client connection closed
2021-09-13 22:19:40,646   INFO       server.py    client connected: ('127.0.0.1', 56672)
2021-09-13 22:19:40,668   DEBUG      server.py    message reseived {'action': 'presence', 'time': 1631560780.6689079, 'user': {'account_name': 'Катя', 'status': 'online'}, 'type': 'status'}
2021-09-13 22:19:40,669   DEBUG      server.py    the message from the client is being handled
2021-09-13 22:19:40,669   INFO       server.py    a response to the client is generated: {'response': 402, 'error': 'no account with that name'}
2021-09-13 22:19:40,670   DEBUG      server.py    responce was sent to the client
2021-09-13 22:19:40,670   DEBUG      server.py    client connection closed
2021-09-13 22:19:46,809   INFO       server.py    client connected: ('127.0.0.1', 56673)
2021-09-13 22:19:46,833   DEBUG      server.py    message reseived {'action': 'presence', 'time': 1631560786.8336709, 'user': {'account_name': 'Катя', 'status': 'online'}, 'type': 'status'}
2021-09-13 22:19:46,834   DEBUG      server.py    the message from the client is being handled
2021-09-13 22:19:46,834   INFO       server.py    a response to the client is generated: {'response': 402, 'error': 'no account with that name'}
2021-09-13 22:19:46,835   DEBUG      server.py    responce was sent to the client
2021-09-13 22:19:46,835   DEBUG      server.py    client connection closed
2021-09-13 22:21:25,431   INFO       server.py    server started at 7777 and listened all ip
2021-09-13 22:21:32,703   INFO       server.py    client connected: ('127.0.0.1', 61390)
2021-09-13 22:21:32,719   DEBUG      server.py    message reseived {'action': 'presence', 'time': 1631560892.7192757, 'user': {'account_name': 'Катя', 'status': 'online'}, 'type': 'status'}
2021-09-13 22:21:32,750   DEBUG      server.py    the message from the client is being handled
2021-09-13 22:21:32,750   INFO       server.py    a response to the client is generated: {'response': 402, 'error': 'no account with that name'}
2021-09-13 22:21:32,750   DEBUG      server.py    responce was sent to the client
2021-09-13 22:21:32,750   DEBUG      server.py    client connection closed
2021-09-13 22:22:43,071   INFO       server.py    client connected: ('127.0.0.1', 61391)
2021-09-13 22:22:43,096   DEBUG      server.py    message reseived {'action': 'presence', 'time': 1631560963.0950649, 'user': {'account_name': 'Катя', 'status': 'online'}, 'type': 'status'}
2021-09-13 22:22:43,097   DEBUG      server.py    the message from the client is being handled
2021-09-13 22:22:43,097   INFO       server.py    a response to the client is generated: {'response': 402, 'error': 'no account with that name'}
2021-09-13 22:22:43,097   DEBUG      server.py    responce was sent to the client
2021-09-13 22:22:43,097   DEBUG      server.py    client connection closed
2021-09-13 22:23:03,651   INFO       server.py    server started at 7777 and listened all ip
2021-09-13 22:23:43,605   INFO       server.py    server started at 7777 and listened all ip
2021-09-13 22:24:12,952   INFO       server.py    server started at 7777 and listened all ip
2021-09-13 22:24:31,344   INFO       server.py    server started at 7777 and listened all ip
2021-09-13 22:27:34,645   CRITICAL   server_log_config.py    critical
2021-09-13 22:27:34,645   ERROR      server_log_config.py    error
2021-09-13 22:27:34,645   WARNING    server_log_config.py    warning
2021-09-13 22:27:34,645   INFO       server_log_config.py    info
2021-09-13 22:27:34,645   DEBUG      server_log_config.py    debug
2021-09-13 22:28:47,612   INFO       server.py    server started at 7777 and listened all ip
2021-09-13 22:28:55,784   INFO       server.py    server started at 7777 and listened all ip
2021-09-13 22:29:01,850   INFO       server.py    client connected: ('127.0.0.1', 55676)
2021-09-13 22:29:01,882   DEBUG      server.py    message reseived {'action': 'presence', 'time': 1631561341.882241, 'user': {'account_name': 'Катя', 'status': 'online'}, 'type': 'status'}
2021-09-13 22:29:01,897   DEBUG      server.py    the message from the client is being handled
2021-09-13 22:29:01,897   INFO       server.py    a response to the client is generated: {'response': 402, 'error': 'no account with that name'}
2021-09-13 22:29:01,897   DEBUG      server.py    responce was sent to the client
2021-09-13 22:29:01,897   DEBUG      server.py    client connection closed
2021-09-13 22:29:51,150   INFO       server.py    client connected: ('127.0.0.1', 55677)
2021-09-13 22:29:51,173   DEBUG      server.py    message reseived {'action': 'presence', 'time': 1631561391.1735573, 'user': {'account_name': 'Катя', 'status': 'online'}, 'type': 'status'}
2021-09-13 22:29:51,174   DEBUG      server.py    the message from the client is being handled
2021-09-13 22:29:51,174   INFO       server.py    a response to the client is generated: {'response': 402, 'error': 'no account with that name'}
2021-09-13 22:29:51,174   DEBUG      server.py    responce was sent to the client
2021-09-13 22:29:51,175   DEBUG      server.py    client connection closed
2021-09-13 22:30:00,432   INFO       server.py    client connected: ('127.0.0.1', 55678)
2021-09-13 22:30:00,447   DEBUG      server.py    message reseived {'action': 'presence', 'time': 1631561400.447908, 'user': {'account_name': 'Катя', 'status': 'online'}, 'type': 'status'}
2021-09-13 22:30:00,447   DEBUG      server.py    the message from the client is being handled
2021-09-13 22:30:00,447   INFO       server.py    a response to the client is generated: {'response': 402, 'error': 'no account with that name'}
2021-09-13 22:30:00,447   DEBUG      server.py    responce was sent to the client
2021-09-13 22:30:00,447   DEBUG      server.py    client connection closed
2021-09-13 22:39:40,058   INFO       server.py    client connected: ('127.0.0.1', 62471)
2021-09-13 22:39:40,086   DEBUG      server.py    message reseived {'action': 'presence', 'time': 1631561980.0855887, 'user': {'account_name': 'Катя', 'status': 'online'}, 'type': 'status'}
2021-09-13 22:39:40,088   DEBUG      server.py    the message from the client is being handled
2021-09-13 22:39:40,088   INFO       server.py    a response to the client is generated: {'response': 402, 'error': 'no account with that name'}
2021-09-13 22:39:40,088   DEBUG      server.py    responce was sent to the client
2021-09-13 22:39:40,088   DEBUG      server.py    client connection closed
2021-09-13 22:39:59,463   INFO       server.py    client connected: ('127.0.0.1', 62472)
2021-09-13 22:39:59,494   DEBUG      server.py    message reseived {'action': 'presence', 'time': 1631561999.4946678, 'user': {'account_name': 'Катя', 'status': 'online'}, 'type': 'status'}
2021-09-13 22:39:59,494   DEBUG      server.py    the message from the client is being handled
2021-09-13 22:39:59,494   INFO       server.py    a response to the client is generated: {'response': 402, 'error': 'no account with that name'}
2021-09-13 22:39:59,494   DEBUG      server.py    responce was sent to the client
2021-09-13 22:39:59,494   DEBUG      server.py    client connection closed
2021-09-13 22:40:26,975   INFO       server.py    client connected: ('127.0.0.1', 51224)
2021-09-13 22:40:26,991   DEBUG      server.py    message reseived {'action': 'presence', 'time': 1631562026.9915764, 'user': {'account_name': 'Катя', 'status': 'online'}, 'type': 'status'}
2021-09-13 22:40:26,991   DEBUG      server.py    the message from the client is being handled
2021-09-13 22:40:26,991   INFO       server.py    a response to the client is generated: {'response': 402, 'error': 'no account with that name'}
2021-09-13 22:40:26,991   DEBUG      server.py    responce was sent to the client
2021-09-13 22:40:26,991   DEBUG      server.py    client connection closed
2021-09-13 22:44:05,179   INFO       server.py    server started at 7777 and listened all ip
2021-09-13 22:44:08,513   INFO       server.py    client connected: ('127.0.0.1', 59642)
2021-09-13 22:44:08,529   DEBUG      server.py    message reseived {'action': 'presence', 'time': 1631562248.529362, 'user': {'account_name': 'Катя', 'status': 'online'}, 'type': 'status'}
2021-09-13 22:44:08,544   DEBUG      server.py    Function: handle_message, args: ({'action': 'presence', 'time': 1631562248.529362, 'user': {'account_name': 'Катя', 'status': 'online'}, 'type': 'status'},), kwargs: {}, called from function main
2021-09-13 22:44:08,544   DEBUG      server.py    the message from the client is being handled
2021-09-13 22:44:08,544   INFO       server.py    a response to the client is generated: {'response': 402, 'error': 'no account with that name'}
2021-09-13 22:44:08,544   DEBUG      server.py    responce was sent to the client
2021-09-13 22:44:08,544   DEBUG      server.py    client connection closed
2021-09-13 22:44:11,393   INFO       server.py    client connected: ('127.0.0.1', 59643)
2021-09-13 22:44:11,409   DEBUG      server.py    message reseived {'action': 'presence', 'time': 1631562251.4090898, 'user': {'account_name': 'Катя', 'status': 'online'}, 'type': 'status'}
2021-09-13 22:44:11,409   DEBUG      server.py    Function: handle_message, args: ({'action': 'presence', 'time': 1631562251.4090898, 'user': {'account_name': 'Катя', 'status': 'online'}, 'type': 'status'},), kwargs: {}, called from function main
2021-09-13 22:44:11,409   DEBUG      server.py    the message from the client is being handled
2021-09-13 22:44:11,409   INFO       server.py    a response to the client is generated: {'response': 402, 'error': 'no account with that name'}
2021-09-13 22:44:11,409   DEBUG      server.py    responce was sent to the client
2021-09-13 22:44:11,409   DEBUG      server.py    client connection closed
2021-09-13 22:44:56,521   INFO       server.py    client connected: ('127.0.0.1', 59644)
2021-09-13 22:44:56,544   DEBUG      server.py    message reseived {'action': 'presence', 'time': 1631562296.5440645, 'user': {'account_name': 'Катя', 'status': 'online'}, 'type': 'status'}
2021-09-13 22:44:56,545   DEBUG      server.py    Function: handle_message, args: ({'action': 'presence', 'time': 1631562296.5440645, 'user': {'account_name': 'Катя', 'status': 'online'}, 'type': 'status'},), kwargs: {}, called from function main
2021-09-13 22:44:56,545   DEBUG      server.py    the message from the client is being handled
2021-09-13 22:44:56,546   INFO       server.py    a response to the client is generated: {'response': 402, 'error': 'no account with that name'}
2021-09-13 22:44:56,546   DEBUG      server.py    responce was sent to the client
2021-09-13 22:44:56,546   DEBUG      server.py    client connection closed
2021-09-13 22:46:55,726   INFO       server.py    server started at 7777 and listened all ip
2021-09-13 22:47:03,491   INFO       server.py    client connected: ('127.0.0.1', 57141)
2021-09-13 22:47:03,523   DEBUG      server.py    message reseived {'action': 'presence', 'time': 1631562423.5230992, 'user': {'account_name': 'Катя', 'status': 'online'}, 'type': 'status'}
2021-09-13 22:47:03,538   DEBUG      server.py    Function: handle_message, args: ({'action': 'presence', 'time': 1631562423.5230992, 'user': {'account_name': 'Катя', 'status': 'online'}, 'type': 'status'},), kwargs: {}, called from function: main
2021-09-13 22:47:03,538   DEBUG      server.py    the message from the client is being handled
2021-09-13 22:47:03,538   INFO       server.py    a response to the client is generated: {'response': 402, 'error': 'no account with that name'}
2021-09-13 22:47:03,538   DEBUG      server.py    responce was sent to the client
2021-09-13 22:47:03,538   DEBUG      server.py    client connection closed
2021-09-13 22:48:45,643   INFO       server.py    client connected: ('127.0.0.1', 57142)
2021-09-13 22:48:45,669   DEBUG      server.py    message reseived {'action': 'presence', 'time': 1631562525.669011, 'user': {'account_name': 'Катя', 'status': 'online'}, 'type': 'status'}
2021-09-13 22:48:45,670   DEBUG      server.py    Function: handle_message, args: ({'action': 'presence', 'time': 1631562525.669011, 'user': {'account_name': 'Катя', 'status': 'online'}, 'type': 'status'},), kwargs: {}, called from function: main
2021-09-13 22:48:45,670   DEBUG      server.py    the message from the client is being handled
2021-09-13 22:48:45,670   INFO       server.py    a response to the client is generated: {'response': 402, 'error': 'no account with that name'}
2021-09-13 22:48:45,671   DEBUG      server.py    responce was sent to the client
2021-09-13 22:48:45,671   DEBUG      server.py    client connection closed
2021-09-13 22:48:58,180   INFO       server.py    client connected: ('127.0.0.1', 57143)
2021-09-13 22:48:58,200   DEBUG      server.py    message reseived {'action': 'presence', 'time': 1631562538.2009182, 'user': {'account_name': 'Guest', 'status': 'online'}, 'type': 'status'}
2021-09-13 22:48:58,201   DEBUG      server.py    Function: handle_message, args: ({'action': 'presence', 'time': 1631562538.2009182, 'user': {'account_name': 'Guest', 'status': 'online'}, 'type': 'status'},), kwargs: {}, called from function: main
2021-09-13 22:48:58,201   DEBUG      server.py    the message from the client is being handled
2021-09-13 22:48:58,201   INFO       server.py    a response to the client is generated: {'response': 200}
2021-09-13 22:48:58,201   DEBUG      server.py    responce was sent to the client
2021-09-13 22:48:58,201   DEBUG      server.py    client connection closed
2021-09-13 22:49:30,520   INFO       server.py    client connected: ('127.0.0.1', 57144)
2021-09-13 22:49:30,567   DEBUG      server.py    message reseived {'action': 'presence', 'time': 1631562570.5671415, 'user': {'account_name': 'Guest', 'status': 'online'}, 'type': 'status'}
2021-09-13 22:49:30,567   DEBUG      server.py    Function: handle_message, args: ({'action': 'presence', 'time': 1631562570.5671415, 'user': {'account_name': 'Guest', 'status': 'online'}, 'type': 'status'},), kwargs: {}, called from function: main
2021-09-13 22:49:30,567   DEBUG      server.py    the message from the client is being handled
2021-09-13 22:49:30,567   INFO       server.py    a response to the client is generated: {'response': 200}
2021-09-13 22:49:30,567   DEBUG      server.py    responce was sent to the client
2021-09-13 22:49:30,567   DEBUG      server.py    client connection closed
2021-09-13 22:50:53,019   INFO       server.py    client connected: ('127.0.0.1', 57145)
2021-09-13 22:50:53,050   DEBUG      server.py    message reseived {'action': 'presence', 'time': 1631562653.050401, 'user': {'account_name': 'Guest', 'status': 'online'}, 'type': 'status'}
2021-09-13 22:50:53,050   DEBUG      server.py    Function: handle_message, args: ({'action': 'presence', 'time': 1631562653.050401, 'user': {'account_name': 'Guest', 'status': 'online'}, 'type': 'status'},), kwargs: {}, called from function: main
2021-09-13 22:50:53,050   DEBUG      server.py    the message from the client is being handled
2021-09-13 22:50:53,050   INFO       server.py    a response to the client is generated: {'response': 200}
2021-09-13 22:50:53,050   DEBUG      server.py    responce was sent to the client
2021-09-13 22:50:53,050   DEBUG      server.py    client connection closed
2021-09-13 22:51:04,856   INFO       server.py    server started at 7777 and listened all ip
2021-09-13 22:51:20,366   INFO       server.py    client connected: ('127.0.0.1', 57146)
2021-09-13 22:51:20,381   INFO       server.py    message reseived {'action': 'presence', 'time': 1631562680.38182, 'user': {'account_name': 'Guest', 'status': 'online'}, 'type': 'status'}
2021-09-13 22:51:20,413   DEBUG      server.py    Function: handle_message, args: ({'action': 'presence', 'time': 1631562680.38182, 'user': {'account_name': 'Guest', 'status': 'online'}, 'type': 'status'},), kwargs: {}, called from function: main
2021-09-13 22:51:20,413   DEBUG      server.py    the message from the client is being handled
2021-09-13 22:51:20,413   DEBUG      server.py    a response to the client is generated: {'response': 200}
2021-09-13 22:51:20,413   DEBUG      server.py    responce was sent to the client
2021-09-13 22:51:20,413   DEBUG      server.py    client connection closed
2021-09-13 22:52:37,474   INFO       server.py    client connected: ('127.0.0.1', 56657)
2021-09-13 22:52:37,505   INFO       server.py    message reseived {'action': 'presence', 'time': 1631562757.5057926, 'user': {'account_name': 'Guest', 'status': 'online'}, 'type': 'status'}
2021-09-13 22:52:37,505   DEBUG      server.py    Function: handle_message, args: ({'action': 'presence', 'time': 1631562757.5057926, 'user': {'account_name': 'Guest', 'status': 'online'}, 'type': 'status'},), kwargs: {}, called from function: main
2021-09-13 22:52:37,505   DEBUG      server.py    the message from the client is being handled
2021-09-13 22:52:37,505   DEBUG      server.py    a response to the client is generated: {'response': 200}
2021-09-13 22:52:37,505   DEBUG      server.py    responce was sent to the client
2021-09-13 22:52:37,505   DEBUG      server.py    client connection closed
2021-09-13 22:52:49,776   INFO       server.py    server started at 7777 and listened all ip
2021-09-13 22:52:52,603   INFO       server.py    client connected: ('127.0.0.1', 56658)
2021-09-13 22:52:52,635   DEBUG      server.py    message reseived {'action': 'presence', 'time': 1631562772.6350973, 'user': {'account_name': 'Guest', 'status': 'online'}, 'type': 'status'}
2021-09-13 22:52:52,666   DEBUG      server.py    Function: handle_message, args: ({'action': 'presence', 'time': 1631562772.6350973, 'user': {'account_name': 'Guest', 'status': 'online'}, 'type': 'status'},), kwargs: {}, called from function: main
2021-09-13 22:52:52,666   DEBUG      server.py    the message from the client is being handled
2021-09-13 22:52:52,666   INFO       server.py    Guest: online
2021-09-13 22:52:52,666   DEBUG      server.py    a response to the client is generated: {'response': 200}
2021-09-13 22:52:52,666   DEBUG      server.py    responce was sent to the client
2021-09-13 22:52:52,666   DEBUG      server.py    client connection closed
2021-09-13 22:53:02,263   INFO       server.py    client connected: ('127.0.0.1', 56659)
2021-09-13 22:53:02,279   DEBUG      server.py    message reseived {'action': 'presence', 'time': 1631562782.2792206, 'user': {'account_name': 'Guest', 'status': 'online'}, 'type': 'status'}
2021-09-13 22:53:02,294   DEBUG      server.py    Function: handle_message, args: ({'action': 'presence', 'time': 1631562782.2792206, 'user': {'account_name': 'Guest', 'status': 'online'}, 'type': 'status'},), kwargs: {}, called from function: main
2021-09-13 22:53:02,294   DEBUG      server.py    the message from the client is being handled
2021-09-13 22:53:02,294   INFO       server.py    Guest: online
2021-09-13 22:53:02,294   DEBUG      server.py    a response to the client is generated: {'response': 200}
2021-09-13 22:53:02,294   DEBUG      server.py    responce was sent to the client
2021-09-13 22:53:02,294   DEBUG      server.py    client connection closed
2021-09-13 22:54:02,720   DEBUG      server.py    Function: handle_message, args: ({'time': 1.1, 'user': {'account_name': 'Guest', 'status': 'online'}, 'type': 'status'},), kwargs: {}, called from function: test_handle_message_presence_no_action
2021-09-13 22:54:02,720   DEBUG      server.py    the message from the client is being handled
2021-09-13 22:54:02,720   DEBUG      server.py    Function: handle_message, args: ({'action': 'presence', 'user': {'account_name': 'Guest', 'status': 'online'}, 'type': 'status'},), kwargs: {}, called from function: test_handle_message_presence_no_time
2021-09-13 22:54:02,720   DEBUG      server.py    the message from the client is being handled
2021-09-13 22:54:02,720   DEBUG      server.py    Function: handle_message, args: ({'action': 'wrong', 'time': 1.1, 'type': 'status'},), kwargs: {}, called from function: test_handle_message_presence_no_user
2021-09-13 22:54:02,720   DEBUG      server.py    the message from the client is being handled
2021-09-13 22:54:02,720   DEBUG      server.py    Function: handle_message, args: ({'action': 'presence', 'time': 1.1, 'user': {'account_name': 'Guest', 'status': 'online'}, 'type': 'status'},), kwargs: {}, called from function: test_handle_message_presence_ok
2021-09-13 22:54:02,720   DEBUG      server.py    the message from the client is being handled
2021-09-13 22:54:02,720   INFO       server.py    Guest: online
2021-09-13 22:54:02,735   DEBUG      server.py    Function: handle_message, args: ({'action': 'wrong', 'time': 1.1, 'user': {'account_name': 'Guest', 'status': 'online'}, 'type': 'status'},), kwargs: {}, called from function: test_handle_message_presence_wrong_action
2021-09-13 22:54:02,735   DEBUG      server.py    the message from the client is being handled
2021-09-13 22:54:02,735   DEBUG      server.py    Function: handle_message, args: ({'action': 'presence', 'time': 1.1, 'user': {'account_name': 'Wrong User', 'status': 'online'}, 'type': 'status'},), kwargs: {}, called from function: test_handle_message_presence_wrong_user
2021-09-13 22:54:02,735   DEBUG      server.py    the message from the client is being handled
